### ISSUE TITLE
License information?

### ISSUE THREAD

**Issue by villares** [TomasFerranti/TextureExtractor#1]
Salve Tomas! 

Em 2015 eu perguntei ao El Dahdah se o código ia ser aberto, ele disse que sim. Você pode confirmar pra mim como é a licença? Tem outros repositórios disponíveis? 

Cordialmente,
Alexandre

**Comment by martimpassos** [comment]
Olá Alexandre, tudo bem?

O repositório principal do imagineRio é [este](https://github.com/imaginerio/). Aqui trata-se de uma linha de pesquisa paralela que está sendo desenvolvida em parceria com a Escola de Matemática Aplicada da FGV-RJ, como parte do projeto _Vistas Situadas do Rio de Janeiro_ (uma colaboração entre a Universidade de Rice, responsável imagineRio, e o Instituto Moreira Salles).

**Comment by villares** [comment]
Muito obrigado! Talvez vocês queiram colocar essa informação no README.md / LICESE.txt em algum momento ;)

**Comment by TomasFerranti** [comment]
Oi Alexandre, minhas desculpas pela informação incorreta no README. Modifiquei para ficar mais claro! Obrigado
